# Generated by Django 5.0.2 on 2024-02-21 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_sys', '0002_alter_lesson_course'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payment', models.DateField(verbose_name='дата оплаты')),
                ('total', models.FloatField(verbose_name='сумма оплаты')),
                ('pay_method', models.CharField(choices=[('cash', 'наличными'), ('card', 'картой')], max_length=15, verbose_name='способ оплаты')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms_sys.course', verbose_name='курс')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms_sys.lesson', verbose_name='урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежы',
            },
        ),
    ]
