# Generated by Django 5.0.2 on 2024-03-28 21:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_sys', '0004_subscription'),
        ('users', '0003_alter_payment_options_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_sys.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_payment',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lesson',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_sys.lesson', verbose_name='урок'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
