# Generated by Django 5.0.2 on 2024-03-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_course_alter_payment_date_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Идентификатор платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.PositiveIntegerField(verbose_name='сумма оплаты'),
        ),
    ]
